version: "1.0"
services:
  iris:
    build:
        context: .
        dockerfile: Dockerfile
    tty: true
    stdin_open: true
    runtime: nvidia
    volumes:
      - ./iris:/app                    # Live code mount
      - ./memory:/memory               # persistent memory
      - ./logs:/logs                   # persistent logging
      - ./models:/models               # LLM model access
    environment:
      - NVIDIA_VISIBLE_DEVICES=all
      - NVIDIA_DRIVER_CAPABILITIES=compute,utility
      - MODEL_PATH=/models/mistral-7b-instruct
      - MEMORY_PATH=/memory/memory_bank.json
      - TAGS_PATH=/memory/tags.json
      - LOG_PATH=/logs
    working_dir: /app
    command: bash -c "python main.py"

